/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.trader.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.trader.parser.antlr.internal.InternalTraderParser;
import uk.ac.kcl.inf.trader.services.TraderGrammarAccess;

public class TraderParser extends AbstractAntlrParser {

	@Inject
	private TraderGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTraderParser createParser(XtextTokenStream stream) {
		return new InternalTraderParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TraderProgram";
	}

	public TraderGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TraderGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
