/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.trader.trader;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.trader.trader.Action#getQuantity <em>Quantity</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.trader.trader.Action#getTicker <em>Ticker</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.trader.trader.Action#getPrice <em>Price</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getAction()
 * @model
 * @generated
 */
public interface Action extends EObject
{
  /**
   * Returns the value of the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Quantity</em>' attribute.
   * @see #setQuantity(float)
   * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getAction_Quantity()
   * @model
   * @generated
   */
  float getQuantity();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.trader.trader.Action#getQuantity <em>Quantity</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Quantity</em>' attribute.
   * @see #getQuantity()
   * @generated
   */
  void setQuantity(float value);

  /**
   * Returns the value of the '<em><b>Ticker</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ticker</em>' attribute.
   * @see #setTicker(String)
   * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getAction_Ticker()
   * @model
   * @generated
   */
  String getTicker();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.trader.trader.Action#getTicker <em>Ticker</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ticker</em>' attribute.
   * @see #getTicker()
   * @generated
   */
  void setTicker(String value);

  /**
   * Returns the value of the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Price</em>' attribute.
   * @see #setPrice(float)
   * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getAction_Price()
   * @model
   * @generated
   */
  float getPrice();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.trader.trader.Action#getPrice <em>Price</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Price</em>' attribute.
   * @see #getPrice()
   * @generated
   */
  void setPrice(float value);

} // Action
