/**
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader.trader;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connect Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.trader.trader.ConnectStatement#getTickerName <em>Ticker Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.trader.trader.ConnectStatement#getBrokerName <em>Broker Name</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.trader.trader.ConnectStatement#getUsername <em>Username</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.trader.trader.ConnectStatement#getPassword <em>Password</em>}</li>
 *   <li>{@link uk.ac.kcl.inf.trader.trader.ConnectStatement#getTimeframe <em>Timeframe</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getConnectStatement()
 * @model
 * @generated
 */
public interface ConnectStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>Ticker Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ticker Name</em>' containment reference.
   * @see #setTickerName(Expression)
   * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getConnectStatement_TickerName()
   * @model containment="true"
   * @generated
   */
  Expression getTickerName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.trader.trader.ConnectStatement#getTickerName <em>Ticker Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ticker Name</em>' containment reference.
   * @see #getTickerName()
   * @generated
   */
  void setTickerName(Expression value);

  /**
   * Returns the value of the '<em><b>Broker Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Broker Name</em>' containment reference.
   * @see #setBrokerName(Expression)
   * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getConnectStatement_BrokerName()
   * @model containment="true"
   * @generated
   */
  Expression getBrokerName();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.trader.trader.ConnectStatement#getBrokerName <em>Broker Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Broker Name</em>' containment reference.
   * @see #getBrokerName()
   * @generated
   */
  void setBrokerName(Expression value);

  /**
   * Returns the value of the '<em><b>Username</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Username</em>' containment reference.
   * @see #setUsername(Expression)
   * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getConnectStatement_Username()
   * @model containment="true"
   * @generated
   */
  Expression getUsername();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.trader.trader.ConnectStatement#getUsername <em>Username</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Username</em>' containment reference.
   * @see #getUsername()
   * @generated
   */
  void setUsername(Expression value);

  /**
   * Returns the value of the '<em><b>Password</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Password</em>' containment reference.
   * @see #setPassword(Expression)
   * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getConnectStatement_Password()
   * @model containment="true"
   * @generated
   */
  Expression getPassword();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.trader.trader.ConnectStatement#getPassword <em>Password</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Password</em>' containment reference.
   * @see #getPassword()
   * @generated
   */
  void setPassword(Expression value);

  /**
   * Returns the value of the '<em><b>Timeframe</b></em>' attribute.
   * The literals are from the enumeration {@link uk.ac.kcl.inf.trader.trader.TimeFrameDef}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timeframe</em>' attribute.
   * @see uk.ac.kcl.inf.trader.trader.TimeFrameDef
   * @see #setTimeframe(TimeFrameDef)
   * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getConnectStatement_Timeframe()
   * @model
   * @generated
   */
  TimeFrameDef getTimeframe();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.trader.trader.ConnectStatement#getTimeframe <em>Timeframe</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Timeframe</em>' attribute.
   * @see uk.ac.kcl.inf.trader.trader.TimeFrameDef
   * @see #getTimeframe()
   * @generated
   */
  void setTimeframe(TimeFrameDef value);

} // ConnectStatement
