/**
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader.trader;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>List Bots Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.trader.trader.ListBotsStatement#getListCommand <em>List Command</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getListBotsStatement()
 * @model
 * @generated
 */
public interface ListBotsStatement extends Statement
{
  /**
   * Returns the value of the '<em><b>List Command</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>List Command</em>' attribute.
   * @see #setListCommand(String)
   * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getListBotsStatement_ListCommand()
   * @model
   * @generated
   */
  String getListCommand();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.trader.trader.ListBotsStatement#getListCommand <em>List Command</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>List Command</em>' attribute.
   * @see #getListCommand()
   * @generated
   */
  void setListCommand(String value);

} // ListBotsStatement
