/**
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader.trader;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Real Variable Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.trader.trader.RealVariableDeclaration#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getRealVariableDeclaration()
 * @model
 * @generated
 */
public interface RealVariableDeclaration extends VariableDeclaration
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(float)
   * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getRealVariableDeclaration_Value()
   * @model
   * @generated
   */
  float getValue();

  /**
   * Sets the value of the '{@link uk.ac.kcl.inf.trader.trader.RealVariableDeclaration#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(float value);

} // RealVariableDeclaration
