/**
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader.trader;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>String Primary</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getStringPrimary()
 * @model
 * @generated
 */
public interface StringPrimary extends EObject
{
} // StringPrimary
