/**
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader.trader;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Time Frame Def</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.trader.trader.TraderPackage#getTimeFrameDef()
 * @model
 * @generated
 */
public enum TimeFrameDef implements Enumerator
{
  /**
   * The '<em><b>M1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M1_VALUE
   * @generated
   * @ordered
   */
  M1(0, "M1", "M1"),

  /**
   * The '<em><b>M2</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M2_VALUE
   * @generated
   * @ordered
   */
  M2(1, "M2", "M2"),

  /**
   * The '<em><b>M3</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M3_VALUE
   * @generated
   * @ordered
   */
  M3(2, "M3", "M3"),

  /**
   * The '<em><b>M4</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M4_VALUE
   * @generated
   * @ordered
   */
  M4(3, "M4", "M4"),

  /**
   * The '<em><b>M5</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M5_VALUE
   * @generated
   * @ordered
   */
  M5(4, "M5", "M5"),

  /**
   * The '<em><b>M6</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M6_VALUE
   * @generated
   * @ordered
   */
  M6(5, "M6", "M6"),

  /**
   * The '<em><b>M10</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M10_VALUE
   * @generated
   * @ordered
   */
  M10(6, "M10", "M10"),

  /**
   * The '<em><b>M12</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M12_VALUE
   * @generated
   * @ordered
   */
  M12(7, "M12", "M12"),

  /**
   * The '<em><b>M20</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M20_VALUE
   * @generated
   * @ordered
   */
  M20(8, "M20", "M20"),

  /**
   * The '<em><b>M30</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M30_VALUE
   * @generated
   * @ordered
   */
  M30(9, "M30", "M30"),

  /**
   * The '<em><b>H1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H1_VALUE
   * @generated
   * @ordered
   */
  H1(10, "H1", "H1"),

  /**
   * The '<em><b>H2</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H2_VALUE
   * @generated
   * @ordered
   */
  H2(11, "H2", "H2"),

  /**
   * The '<em><b>H3</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H3_VALUE
   * @generated
   * @ordered
   */
  H3(12, "H3", "H3"),

  /**
   * The '<em><b>H4</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H4_VALUE
   * @generated
   * @ordered
   */
  H4(13, "H4", "H4"),

  /**
   * The '<em><b>H6</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H6_VALUE
   * @generated
   * @ordered
   */
  H6(14, "H6", "H6"),

  /**
   * The '<em><b>H8</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H8_VALUE
   * @generated
   * @ordered
   */
  H8(15, "H8", "H8"),

  /**
   * The '<em><b>H12</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H12_VALUE
   * @generated
   * @ordered
   */
  H12(16, "H12", "H12"),

  /**
   * The '<em><b>D1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #D1_VALUE
   * @generated
   * @ordered
   */
  D1(17, "D1", "D1"),

  /**
   * The '<em><b>W1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #W1_VALUE
   * @generated
   * @ordered
   */
  W1(18, "W1", "W1"),

  /**
   * The '<em><b>MN1</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MN1_VALUE
   * @generated
   * @ordered
   */
  MN1(19, "MN1", "MN1");

  /**
   * The '<em><b>M1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M1
   * @model
   * @generated
   * @ordered
   */
  public static final int M1_VALUE = 0;

  /**
   * The '<em><b>M2</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M2
   * @model
   * @generated
   * @ordered
   */
  public static final int M2_VALUE = 1;

  /**
   * The '<em><b>M3</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M3
   * @model
   * @generated
   * @ordered
   */
  public static final int M3_VALUE = 2;

  /**
   * The '<em><b>M4</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M4
   * @model
   * @generated
   * @ordered
   */
  public static final int M4_VALUE = 3;

  /**
   * The '<em><b>M5</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M5
   * @model
   * @generated
   * @ordered
   */
  public static final int M5_VALUE = 4;

  /**
   * The '<em><b>M6</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M6
   * @model
   * @generated
   * @ordered
   */
  public static final int M6_VALUE = 5;

  /**
   * The '<em><b>M10</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M10
   * @model
   * @generated
   * @ordered
   */
  public static final int M10_VALUE = 6;

  /**
   * The '<em><b>M12</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M12
   * @model
   * @generated
   * @ordered
   */
  public static final int M12_VALUE = 7;

  /**
   * The '<em><b>M20</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M20
   * @model
   * @generated
   * @ordered
   */
  public static final int M20_VALUE = 8;

  /**
   * The '<em><b>M30</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #M30
   * @model
   * @generated
   * @ordered
   */
  public static final int M30_VALUE = 9;

  /**
   * The '<em><b>H1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H1
   * @model
   * @generated
   * @ordered
   */
  public static final int H1_VALUE = 10;

  /**
   * The '<em><b>H2</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H2
   * @model
   * @generated
   * @ordered
   */
  public static final int H2_VALUE = 11;

  /**
   * The '<em><b>H3</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H3
   * @model
   * @generated
   * @ordered
   */
  public static final int H3_VALUE = 12;

  /**
   * The '<em><b>H4</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H4
   * @model
   * @generated
   * @ordered
   */
  public static final int H4_VALUE = 13;

  /**
   * The '<em><b>H6</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H6
   * @model
   * @generated
   * @ordered
   */
  public static final int H6_VALUE = 14;

  /**
   * The '<em><b>H8</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H8
   * @model
   * @generated
   * @ordered
   */
  public static final int H8_VALUE = 15;

  /**
   * The '<em><b>H12</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #H12
   * @model
   * @generated
   * @ordered
   */
  public static final int H12_VALUE = 16;

  /**
   * The '<em><b>D1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #D1
   * @model
   * @generated
   * @ordered
   */
  public static final int D1_VALUE = 17;

  /**
   * The '<em><b>W1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #W1
   * @model
   * @generated
   * @ordered
   */
  public static final int W1_VALUE = 18;

  /**
   * The '<em><b>MN1</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MN1
   * @model
   * @generated
   * @ordered
   */
  public static final int MN1_VALUE = 19;

  /**
   * An array of all the '<em><b>Time Frame Def</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final TimeFrameDef[] VALUES_ARRAY =
    new TimeFrameDef[]
    {
      M1,
      M2,
      M3,
      M4,
      M5,
      M6,
      M10,
      M12,
      M20,
      M30,
      H1,
      H2,
      H3,
      H4,
      H6,
      H8,
      H12,
      D1,
      W1,
      MN1,
    };

  /**
   * A public read-only list of all the '<em><b>Time Frame Def</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<TimeFrameDef> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Time Frame Def</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TimeFrameDef get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TimeFrameDef result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Time Frame Def</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TimeFrameDef getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      TimeFrameDef result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Time Frame Def</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static TimeFrameDef get(int value)
  {
    switch (value)
    {
      case M1_VALUE: return M1;
      case M2_VALUE: return M2;
      case M3_VALUE: return M3;
      case M4_VALUE: return M4;
      case M5_VALUE: return M5;
      case M6_VALUE: return M6;
      case M10_VALUE: return M10;
      case M12_VALUE: return M12;
      case M20_VALUE: return M20;
      case M30_VALUE: return M30;
      case H1_VALUE: return H1;
      case H2_VALUE: return H2;
      case H3_VALUE: return H3;
      case H4_VALUE: return H4;
      case H6_VALUE: return H6;
      case H8_VALUE: return H8;
      case H12_VALUE: return H12;
      case D1_VALUE: return D1;
      case W1_VALUE: return W1;
      case MN1_VALUE: return MN1;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private TimeFrameDef(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //TimeFrameDef
