/**
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.trader.trader;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.trader.trader.TraderFactory
 * @model kind="package"
 * @generated
 */
public interface TraderPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "trader";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/trader/Trader";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "trader";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TraderPackage eINSTANCE = uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.TraderProgramImpl <em>Program</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderProgramImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getTraderProgram()
   * @generated
   */
  int TRADER_PROGRAM = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRADER_PROGRAM__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Program</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRADER_PROGRAM_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.StatementImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.ConnectImpl <em>Connect</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.ConnectImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getConnect()
   * @generated
   */
  int CONNECT = 2;

  /**
   * The feature id for the '<em><b>Broker Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT__BROKER_NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parameters</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT__PARAMETERS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Connect</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.ConnectParametersImpl <em>Connect Parameters</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.ConnectParametersImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getConnectParameters()
   * @generated
   */
  int CONNECT_PARAMETERS = 3;

  /**
   * The feature id for the '<em><b>Username</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT_PARAMETERS__USERNAME = 0;

  /**
   * The feature id for the '<em><b>Password</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT_PARAMETERS__PASSWORD = 1;

  /**
   * The feature id for the '<em><b>Leverage</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT_PARAMETERS__LEVERAGE = 2;

  /**
   * The feature id for the '<em><b>Money</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT_PARAMETERS__MONEY = 3;

  /**
   * The feature id for the '<em><b>Timeframe</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT_PARAMETERS__TIMEFRAME = 4;

  /**
   * The number of structural features of the '<em>Connect Parameters</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONNECT_PARAMETERS_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.TradingBotImpl <em>Trading Bot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.TradingBotImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getTradingBot()
   * @generated
   */
  int TRADING_BOT = 4;

  /**
   * The feature id for the '<em><b>Strategy</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRADING_BOT__STRATEGY = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Funds</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRADING_BOT__FUNDS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Trading Bot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRADING_BOT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.ExecuteImpl <em>Execute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.ExecuteImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getExecute()
   * @generated
   */
  int EXECUTE = 5;

  /**
   * The feature id for the '<em><b>Bots</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXECUTE__BOTS = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Execute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXECUTE_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.VariableDeclarationImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.LoopStatementImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getLoopStatement()
   * @generated
   */
  int LOOP_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>Count</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT__COUNT = STATEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT__STATEMENTS = STATEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Loop Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOOP_STATEMENT_FEATURE_COUNT = STATEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.IntExpressionImpl <em>Int Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.IntExpressionImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getIntExpression()
   * @generated
   */
  int INT_EXPRESSION = 8;

  /**
   * The number of structural features of the '<em>Int Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.IntLiteralImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 9;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VAL = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.IntVarExpressionImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getIntVarExpression()
   * @generated
   */
  int INT_VAR_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION__VAR = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.ActionImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getAction()
   * @generated
   */
  int ACTION = 11;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__QUANTITY = 0;

  /**
   * The feature id for the '<em><b>Ticker</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__TICKER = 1;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__PRICE = 2;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.BuyImpl <em>Buy</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.BuyImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getBuy()
   * @generated
   */
  int BUY = 12;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUY__QUANTITY = ACTION__QUANTITY;

  /**
   * The feature id for the '<em><b>Ticker</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUY__TICKER = ACTION__TICKER;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUY__PRICE = ACTION__PRICE;

  /**
   * The number of structural features of the '<em>Buy</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUY_FEATURE_COUNT = ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.SellImpl <em>Sell</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.SellImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getSell()
   * @generated
   */
  int SELL = 13;

  /**
   * The feature id for the '<em><b>Quantity</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELL__QUANTITY = ACTION__QUANTITY;

  /**
   * The feature id for the '<em><b>Ticker</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELL__TICKER = ACTION__TICKER;

  /**
   * The feature id for the '<em><b>Price</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELL__PRICE = ACTION__PRICE;

  /**
   * The number of structural features of the '<em>Sell</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELL_FEATURE_COUNT = ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.AdditionImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__OPERATOR = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.impl.MultiplicationImpl
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 15;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = INT_EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__OPERATOR = INT_EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = INT_EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = INT_EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.trader.trader.StrategyDef <em>Strategy Def</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.trader.trader.StrategyDef
   * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getStrategyDef()
   * @generated
   */
  int STRATEGY_DEF = 16;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.TraderProgram <em>Program</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Program</em>'.
   * @see uk.ac.kcl.inf.trader.trader.TraderProgram
   * @generated
   */
  EClass getTraderProgram();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.trader.trader.TraderProgram#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.trader.trader.TraderProgram#getStatements()
   * @see #getTraderProgram()
   * @generated
   */
  EReference getTraderProgram_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.Connect <em>Connect</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connect</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Connect
   * @generated
   */
  EClass getConnect();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.Connect#getBrokerName <em>Broker Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Broker Name</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Connect#getBrokerName()
   * @see #getConnect()
   * @generated
   */
  EAttribute getConnect_BrokerName();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.trader.trader.Connect#getParameters <em>Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Parameters</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Connect#getParameters()
   * @see #getConnect()
   * @generated
   */
  EReference getConnect_Parameters();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.ConnectParameters <em>Connect Parameters</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Connect Parameters</em>'.
   * @see uk.ac.kcl.inf.trader.trader.ConnectParameters
   * @generated
   */
  EClass getConnectParameters();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.ConnectParameters#getUsername <em>Username</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Username</em>'.
   * @see uk.ac.kcl.inf.trader.trader.ConnectParameters#getUsername()
   * @see #getConnectParameters()
   * @generated
   */
  EAttribute getConnectParameters_Username();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.ConnectParameters#getPassword <em>Password</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Password</em>'.
   * @see uk.ac.kcl.inf.trader.trader.ConnectParameters#getPassword()
   * @see #getConnectParameters()
   * @generated
   */
  EAttribute getConnectParameters_Password();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.ConnectParameters#getLeverage <em>Leverage</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Leverage</em>'.
   * @see uk.ac.kcl.inf.trader.trader.ConnectParameters#getLeverage()
   * @see #getConnectParameters()
   * @generated
   */
  EAttribute getConnectParameters_Leverage();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.ConnectParameters#getMoney <em>Money</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Money</em>'.
   * @see uk.ac.kcl.inf.trader.trader.ConnectParameters#getMoney()
   * @see #getConnectParameters()
   * @generated
   */
  EAttribute getConnectParameters_Money();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.ConnectParameters#getTimeframe <em>Timeframe</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Timeframe</em>'.
   * @see uk.ac.kcl.inf.trader.trader.ConnectParameters#getTimeframe()
   * @see #getConnectParameters()
   * @generated
   */
  EAttribute getConnectParameters_Timeframe();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.TradingBot <em>Trading Bot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trading Bot</em>'.
   * @see uk.ac.kcl.inf.trader.trader.TradingBot
   * @generated
   */
  EClass getTradingBot();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.TradingBot#getStrategy <em>Strategy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Strategy</em>'.
   * @see uk.ac.kcl.inf.trader.trader.TradingBot#getStrategy()
   * @see #getTradingBot()
   * @generated
   */
  EAttribute getTradingBot_Strategy();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.TradingBot#getFunds <em>Funds</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Funds</em>'.
   * @see uk.ac.kcl.inf.trader.trader.TradingBot#getFunds()
   * @see #getTradingBot()
   * @generated
   */
  EAttribute getTradingBot_Funds();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.Execute <em>Execute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Execute</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Execute
   * @generated
   */
  EClass getExecute();

  /**
   * Returns the meta object for the reference list '{@link uk.ac.kcl.inf.trader.trader.Execute#getBots <em>Bots</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Bots</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Execute#getBots()
   * @see #getExecute()
   * @generated
   */
  EReference getExecute_Bots();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see uk.ac.kcl.inf.trader.trader.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see uk.ac.kcl.inf.trader.trader.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see uk.ac.kcl.inf.trader.trader.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.LoopStatement <em>Loop Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Loop Statement</em>'.
   * @see uk.ac.kcl.inf.trader.trader.LoopStatement
   * @generated
   */
  EClass getLoopStatement();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.trader.trader.LoopStatement#getCount <em>Count</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Count</em>'.
   * @see uk.ac.kcl.inf.trader.trader.LoopStatement#getCount()
   * @see #getLoopStatement()
   * @generated
   */
  EReference getLoopStatement_Count();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.trader.trader.LoopStatement#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see uk.ac.kcl.inf.trader.trader.LoopStatement#getStatements()
   * @see #getLoopStatement()
   * @generated
   */
  EReference getLoopStatement_Statements();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.IntExpression <em>Int Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Expression</em>'.
   * @see uk.ac.kcl.inf.trader.trader.IntExpression
   * @generated
   */
  EClass getIntExpression();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see uk.ac.kcl.inf.trader.trader.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.IntLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see uk.ac.kcl.inf.trader.trader.IntLiteral#getVal()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Val();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.IntVarExpression <em>Int Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Var Expression</em>'.
   * @see uk.ac.kcl.inf.trader.trader.IntVarExpression
   * @generated
   */
  EClass getIntVarExpression();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.trader.trader.IntVarExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see uk.ac.kcl.inf.trader.trader.IntVarExpression#getVar()
   * @see #getIntVarExpression()
   * @generated
   */
  EReference getIntVarExpression_Var();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.Action#getQuantity <em>Quantity</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Quantity</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Action#getQuantity()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Quantity();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.Action#getTicker <em>Ticker</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ticker</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Action#getTicker()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Ticker();

  /**
   * Returns the meta object for the attribute '{@link uk.ac.kcl.inf.trader.trader.Action#getPrice <em>Price</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Price</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Action#getPrice()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Price();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.Buy <em>Buy</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Buy</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Buy
   * @generated
   */
  EClass getBuy();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.Sell <em>Sell</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sell</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Sell
   * @generated
   */
  EClass getSell();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.trader.trader.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.inf.trader.trader.Addition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Addition#getOperator()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.trader.trader.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.trader.trader.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link uk.ac.kcl.inf.trader.trader.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the attribute list '{@link uk.ac.kcl.inf.trader.trader.Multiplication#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Multiplication#getOperator()
   * @see #getMultiplication()
   * @generated
   */
  EAttribute getMultiplication_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link uk.ac.kcl.inf.trader.trader.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see uk.ac.kcl.inf.trader.trader.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the meta object for enum '{@link uk.ac.kcl.inf.trader.trader.StrategyDef <em>Strategy Def</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Strategy Def</em>'.
   * @see uk.ac.kcl.inf.trader.trader.StrategyDef
   * @generated
   */
  EEnum getStrategyDef();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TraderFactory getTraderFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.TraderProgramImpl <em>Program</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderProgramImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getTraderProgram()
     * @generated
     */
    EClass TRADER_PROGRAM = eINSTANCE.getTraderProgram();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRADER_PROGRAM__STATEMENTS = eINSTANCE.getTraderProgram_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.StatementImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.ConnectImpl <em>Connect</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.ConnectImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getConnect()
     * @generated
     */
    EClass CONNECT = eINSTANCE.getConnect();

    /**
     * The meta object literal for the '<em><b>Broker Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECT__BROKER_NAME = eINSTANCE.getConnect_BrokerName();

    /**
     * The meta object literal for the '<em><b>Parameters</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONNECT__PARAMETERS = eINSTANCE.getConnect_Parameters();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.ConnectParametersImpl <em>Connect Parameters</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.ConnectParametersImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getConnectParameters()
     * @generated
     */
    EClass CONNECT_PARAMETERS = eINSTANCE.getConnectParameters();

    /**
     * The meta object literal for the '<em><b>Username</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECT_PARAMETERS__USERNAME = eINSTANCE.getConnectParameters_Username();

    /**
     * The meta object literal for the '<em><b>Password</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECT_PARAMETERS__PASSWORD = eINSTANCE.getConnectParameters_Password();

    /**
     * The meta object literal for the '<em><b>Leverage</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECT_PARAMETERS__LEVERAGE = eINSTANCE.getConnectParameters_Leverage();

    /**
     * The meta object literal for the '<em><b>Money</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECT_PARAMETERS__MONEY = eINSTANCE.getConnectParameters_Money();

    /**
     * The meta object literal for the '<em><b>Timeframe</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONNECT_PARAMETERS__TIMEFRAME = eINSTANCE.getConnectParameters_Timeframe();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.TradingBotImpl <em>Trading Bot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.TradingBotImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getTradingBot()
     * @generated
     */
    EClass TRADING_BOT = eINSTANCE.getTradingBot();

    /**
     * The meta object literal for the '<em><b>Strategy</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRADING_BOT__STRATEGY = eINSTANCE.getTradingBot_Strategy();

    /**
     * The meta object literal for the '<em><b>Funds</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRADING_BOT__FUNDS = eINSTANCE.getTradingBot_Funds();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.ExecuteImpl <em>Execute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.ExecuteImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getExecute()
     * @generated
     */
    EClass EXECUTE = eINSTANCE.getExecute();

    /**
     * The meta object literal for the '<em><b>Bots</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXECUTE__BOTS = eINSTANCE.getExecute_Bots();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.VariableDeclarationImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.LoopStatementImpl <em>Loop Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.LoopStatementImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getLoopStatement()
     * @generated
     */
    EClass LOOP_STATEMENT = eINSTANCE.getLoopStatement();

    /**
     * The meta object literal for the '<em><b>Count</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP_STATEMENT__COUNT = eINSTANCE.getLoopStatement_Count();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOOP_STATEMENT__STATEMENTS = eINSTANCE.getLoopStatement_Statements();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.IntExpressionImpl <em>Int Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.IntExpressionImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getIntExpression()
     * @generated
     */
    EClass INT_EXPRESSION = eINSTANCE.getIntExpression();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.IntLiteralImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VAL = eINSTANCE.getIntLiteral_Val();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.IntVarExpressionImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getIntVarExpression()
     * @generated
     */
    EClass INT_VAR_EXPRESSION = eINSTANCE.getIntVarExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INT_VAR_EXPRESSION__VAR = eINSTANCE.getIntVarExpression_Var();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.ActionImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Quantity</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__QUANTITY = eINSTANCE.getAction_Quantity();

    /**
     * The meta object literal for the '<em><b>Ticker</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__TICKER = eINSTANCE.getAction_Ticker();

    /**
     * The meta object literal for the '<em><b>Price</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__PRICE = eINSTANCE.getAction_Price();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.BuyImpl <em>Buy</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.BuyImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getBuy()
     * @generated
     */
    EClass BUY = eINSTANCE.getBuy();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.SellImpl <em>Sell</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.SellImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getSell()
     * @generated
     */
    EClass SELL = eINSTANCE.getSell();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.AdditionImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__OPERATOR = eINSTANCE.getAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.impl.MultiplicationImpl
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION__OPERATOR = eINSTANCE.getMultiplication_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.trader.trader.StrategyDef <em>Strategy Def</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.trader.trader.StrategyDef
     * @see uk.ac.kcl.inf.trader.trader.impl.TraderPackageImpl#getStrategyDef()
     * @generated
     */
    EEnum STRATEGY_DEF = eINSTANCE.getStrategyDef();

  }

} //TraderPackage
