/*
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class TraderGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class TraderProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.TraderProgram");
		private final Assignment cStatementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cStatementsStatementParserRuleCall_0 = (RuleCall)cStatementsAssignment.eContents().get(0);
		
		//TraderProgram:
		//    statements+=Statement*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//statements+=Statement*
		public Assignment getStatementsAssignment() { return cStatementsAssignment; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_0() { return cStatementsStatementParserRuleCall_0; }
	}
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cConnectParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTradingBotParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cListBotsParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cExecuteParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cStopParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cVariableDeclarationParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cLoopStatementParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		
		//Statement:
		//    Connect | TradingBot | ListBots | Execute | Stop | VariableDeclaration | LoopStatement
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Connect | TradingBot | ListBots | Execute | Stop | VariableDeclaration | LoopStatement
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Connect
		public RuleCall getConnectParserRuleCall_0() { return cConnectParserRuleCall_0; }
		
		//TradingBot
		public RuleCall getTradingBotParserRuleCall_1() { return cTradingBotParserRuleCall_1; }
		
		//ListBots
		public RuleCall getListBotsParserRuleCall_2() { return cListBotsParserRuleCall_2; }
		
		//Execute
		public RuleCall getExecuteParserRuleCall_3() { return cExecuteParserRuleCall_3; }
		
		//Stop
		public RuleCall getStopParserRuleCall_4() { return cStopParserRuleCall_4; }
		
		//VariableDeclaration
		public RuleCall getVariableDeclarationParserRuleCall_5() { return cVariableDeclarationParserRuleCall_5; }
		
		//LoopStatement
		public RuleCall getLoopStatementParserRuleCall_6() { return cLoopStatementParserRuleCall_6; }
	}
	public class ConnectElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.Connect");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConnectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cToKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cBrokerKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cBrokerNameAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cBrokerNameIDTerminalRuleCall_3_0 = (RuleCall)cBrokerNameAssignment_3.eContents().get(0);
		private final Keyword cWithKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cParametersAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cParametersConnectParametersParserRuleCall_5_0 = (RuleCall)cParametersAssignment_5.eContents().get(0);
		
		//Connect:
		//    "connect" "to" "broker" brokerName = ID "with" ( parameters=ConnectParameters)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"connect" "to" "broker" brokerName = ID "with" ( parameters=ConnectParameters)?
		public Group getGroup() { return cGroup; }
		
		//"connect"
		public Keyword getConnectKeyword_0() { return cConnectKeyword_0; }
		
		//"to"
		public Keyword getToKeyword_1() { return cToKeyword_1; }
		
		//"broker"
		public Keyword getBrokerKeyword_2() { return cBrokerKeyword_2; }
		
		//brokerName = ID
		public Assignment getBrokerNameAssignment_3() { return cBrokerNameAssignment_3; }
		
		//ID
		public RuleCall getBrokerNameIDTerminalRuleCall_3_0() { return cBrokerNameIDTerminalRuleCall_3_0; }
		
		//"with"
		public Keyword getWithKeyword_4() { return cWithKeyword_4; }
		
		//( parameters=ConnectParameters)?
		public Assignment getParametersAssignment_5() { return cParametersAssignment_5; }
		
		//ConnectParameters
		public RuleCall getParametersConnectParametersParserRuleCall_5_0() { return cParametersConnectParametersParserRuleCall_5_0; }
	}
	public class ConnectParametersElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.ConnectParameters");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUsernameKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUsernameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUsernameSTRINGTerminalRuleCall_1_0 = (RuleCall)cUsernameAssignment_1.eContents().get(0);
		private final Keyword cCommaKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cPasswordKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cPasswordAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cPasswordSTRINGTerminalRuleCall_4_0 = (RuleCall)cPasswordAssignment_4.eContents().get(0);
		private final Keyword cCommaKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeverageKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cLeverageAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLeverageREALParserRuleCall_7_0 = (RuleCall)cLeverageAssignment_7.eContents().get(0);
		private final Keyword cCommaKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cMoneyKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cMoneyAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cMoneyREALParserRuleCall_10_0 = (RuleCall)cMoneyAssignment_10.eContents().get(0);
		private final Keyword cCommaKeyword_11 = (Keyword)cGroup.eContents().get(11);
		private final Keyword cTimeframeKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Assignment cTimeframeAssignment_13 = (Assignment)cGroup.eContents().get(13);
		private final RuleCall cTimeframeSTRINGTerminalRuleCall_13_0 = (RuleCall)cTimeframeAssignment_13.eContents().get(0);
		
		//ConnectParameters:
		//    "username" username=STRING ","
		//    "password" password=STRING ","
		//    "leverage" leverage=REAL ","
		//    "money" money=REAL ","
		//    "timeframe" timeframe=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"username" username=STRING ","
		//"password" password=STRING ","
		//"leverage" leverage=REAL ","
		//"money" money=REAL ","
		//"timeframe" timeframe=STRING
		public Group getGroup() { return cGroup; }
		
		//"username"
		public Keyword getUsernameKeyword_0() { return cUsernameKeyword_0; }
		
		//username=STRING
		public Assignment getUsernameAssignment_1() { return cUsernameAssignment_1; }
		
		//STRING
		public RuleCall getUsernameSTRINGTerminalRuleCall_1_0() { return cUsernameSTRINGTerminalRuleCall_1_0; }
		
		//","
		public Keyword getCommaKeyword_2() { return cCommaKeyword_2; }
		
		//"password"
		public Keyword getPasswordKeyword_3() { return cPasswordKeyword_3; }
		
		//password=STRING
		public Assignment getPasswordAssignment_4() { return cPasswordAssignment_4; }
		
		//STRING
		public RuleCall getPasswordSTRINGTerminalRuleCall_4_0() { return cPasswordSTRINGTerminalRuleCall_4_0; }
		
		//","
		public Keyword getCommaKeyword_5() { return cCommaKeyword_5; }
		
		//"leverage"
		public Keyword getLeverageKeyword_6() { return cLeverageKeyword_6; }
		
		//leverage=REAL
		public Assignment getLeverageAssignment_7() { return cLeverageAssignment_7; }
		
		//REAL
		public RuleCall getLeverageREALParserRuleCall_7_0() { return cLeverageREALParserRuleCall_7_0; }
		
		//","
		public Keyword getCommaKeyword_8() { return cCommaKeyword_8; }
		
		//"money"
		public Keyword getMoneyKeyword_9() { return cMoneyKeyword_9; }
		
		//money=REAL
		public Assignment getMoneyAssignment_10() { return cMoneyAssignment_10; }
		
		//REAL
		public RuleCall getMoneyREALParserRuleCall_10_0() { return cMoneyREALParserRuleCall_10_0; }
		
		//","
		public Keyword getCommaKeyword_11() { return cCommaKeyword_11; }
		
		//"timeframe"
		public Keyword getTimeframeKeyword_12() { return cTimeframeKeyword_12; }
		
		//timeframe=STRING
		public Assignment getTimeframeAssignment_13() { return cTimeframeAssignment_13; }
		
		//STRING
		public RuleCall getTimeframeSTRINGTerminalRuleCall_13_0() { return cTimeframeSTRINGTerminalRuleCall_13_0; }
	}
	public class TradingBotElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.TradingBot");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCreateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cBotKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cBotNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cBotNameIDTerminalRuleCall_2_0 = (RuleCall)cBotNameAssignment_2.eContents().get(0);
		private final Keyword cWithKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStrategyAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStrategyStrategyDefEnumRuleCall_4_0 = (RuleCall)cStrategyAssignment_4.eContents().get(0);
		private final Keyword cStrategyKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cUsingKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cFundsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cFundsREALParserRuleCall_7_0 = (RuleCall)cFundsAssignment_7.eContents().get(0);
		private final Keyword cFromKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Keyword cMoneyKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//TradingBot:
		//    "create" "bot" botName = ID "with" strategy = StrategyDef "strategy" "using" funds = REAL "from" "money"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"create" "bot" botName = ID "with" strategy = StrategyDef "strategy" "using" funds = REAL "from" "money"
		public Group getGroup() { return cGroup; }
		
		//"create"
		public Keyword getCreateKeyword_0() { return cCreateKeyword_0; }
		
		//"bot"
		public Keyword getBotKeyword_1() { return cBotKeyword_1; }
		
		//botName = ID
		public Assignment getBotNameAssignment_2() { return cBotNameAssignment_2; }
		
		//ID
		public RuleCall getBotNameIDTerminalRuleCall_2_0() { return cBotNameIDTerminalRuleCall_2_0; }
		
		//"with"
		public Keyword getWithKeyword_3() { return cWithKeyword_3; }
		
		//strategy = StrategyDef
		public Assignment getStrategyAssignment_4() { return cStrategyAssignment_4; }
		
		//StrategyDef
		public RuleCall getStrategyStrategyDefEnumRuleCall_4_0() { return cStrategyStrategyDefEnumRuleCall_4_0; }
		
		//"strategy"
		public Keyword getStrategyKeyword_5() { return cStrategyKeyword_5; }
		
		//"using"
		public Keyword getUsingKeyword_6() { return cUsingKeyword_6; }
		
		//funds = REAL
		public Assignment getFundsAssignment_7() { return cFundsAssignment_7; }
		
		//REAL
		public RuleCall getFundsREALParserRuleCall_7_0() { return cFundsREALParserRuleCall_7_0; }
		
		//"from"
		public Keyword getFromKeyword_8() { return cFromKeyword_8; }
		
		//"money"
		public Keyword getMoneyKeyword_9() { return cMoneyKeyword_9; }
	}
	public class ListBotsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.ListBots");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cListCommandAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cListCommandSeeKeyword_0_0 = (Keyword)cListCommandAssignment_0.eContents().get(0);
		private final Keyword cRegisteredKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cBotsKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//ListBots:
		//    listCommand = "see" "registered" "bots"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//listCommand = "see" "registered" "bots"
		public Group getGroup() { return cGroup; }
		
		//listCommand = "see"
		public Assignment getListCommandAssignment_0() { return cListCommandAssignment_0; }
		
		//"see"
		public Keyword getListCommandSeeKeyword_0_0() { return cListCommandSeeKeyword_0_0; }
		
		//"registered"
		public Keyword getRegisteredKeyword_1() { return cRegisteredKeyword_1; }
		
		//"bots"
		public Keyword getBotsKeyword_2() { return cBotsKeyword_2; }
	}
	public class ExecuteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.Execute");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cExecuteCommandAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cExecuteCommandExecuteKeyword_0_0 = (Keyword)cExecuteCommandAssignment_0.eContents().get(0);
		private final Keyword cBotsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Execute:
		//    executeCommand = "execute" "bots"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//executeCommand = "execute" "bots"
		public Group getGroup() { return cGroup; }
		
		//executeCommand = "execute"
		public Assignment getExecuteCommandAssignment_0() { return cExecuteCommandAssignment_0; }
		
		//"execute"
		public Keyword getExecuteCommandExecuteKeyword_0_0() { return cExecuteCommandExecuteKeyword_0_0; }
		
		//"bots"
		public Keyword getBotsKeyword_1() { return cBotsKeyword_1; }
	}
	public class StopElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.Stop");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cStopCommandAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cStopCommandStopKeyword_0_0 = (Keyword)cStopCommandAssignment_0.eContents().get(0);
		private final Keyword cBotsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		
		//Stop:
		//    stopCommand = "stop" "bots"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//stopCommand = "stop" "bots"
		public Group getGroup() { return cGroup; }
		
		//stopCommand = "stop"
		public Assignment getStopCommandAssignment_0() { return cStopCommandAssignment_0; }
		
		//"stop"
		public Keyword getStopCommandStopKeyword_0_0() { return cStopCommandStopKeyword_0_0; }
		
		//"bots"
		public Keyword getBotsKeyword_1() { return cBotsKeyword_1; }
	}
	public class VariableDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.VariableDeclaration");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntVariableDeclarationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStringVariableDeclarationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRealVariableDeclarationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//VariableDeclaration:
		//    IntVariableDeclaration | StringVariableDeclaration | RealVariableDeclaration
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//IntVariableDeclaration | StringVariableDeclaration | RealVariableDeclaration
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntVariableDeclaration
		public RuleCall getIntVariableDeclarationParserRuleCall_0() { return cIntVariableDeclarationParserRuleCall_0; }
		
		//StringVariableDeclaration
		public RuleCall getStringVariableDeclarationParserRuleCall_1() { return cStringVariableDeclarationParserRuleCall_1; }
		
		//RealVariableDeclaration
		public RuleCall getRealVariableDeclarationParserRuleCall_2() { return cRealVariableDeclarationParserRuleCall_2; }
	}
	public class IntVariableDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.IntVariableDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cIntKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueINTTerminalRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		
		//IntVariableDeclaration:
		//    "var" name=ID "=" "int" ":" value=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"var" name=ID "=" "int" ":" value=INT
		public Group getGroup() { return cGroup; }
		
		//"var"
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//"int"
		public Keyword getIntKeyword_3() { return cIntKeyword_3; }
		
		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//value=INT
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_5_0() { return cValueINTTerminalRuleCall_5_0; }
	}
	public class StringVariableDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.StringVariableDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cStringKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueSTRINGTerminalRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		
		//StringVariableDeclaration:
		//    "var" name=ID "=" "String" ":" value=STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"var" name=ID "=" "String" ":" value=STRING
		public Group getGroup() { return cGroup; }
		
		//"var"
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//"String"
		public Keyword getStringKeyword_3() { return cStringKeyword_3; }
		
		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//value=STRING
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_5_0() { return cValueSTRINGTerminalRuleCall_5_0; }
	}
	public class RealVariableDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.RealVariableDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cRealKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cColonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cValueAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cValueREALParserRuleCall_5_0 = (RuleCall)cValueAssignment_5.eContents().get(0);
		
		//RealVariableDeclaration:
		//    "var" name=ID "=" "Real" ":" value=REAL
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"var" name=ID "=" "Real" ":" value=REAL
		public Group getGroup() { return cGroup; }
		
		//"var"
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//"Real"
		public Keyword getRealKeyword_3() { return cRealKeyword_3; }
		
		//":"
		public Keyword getColonKeyword_4() { return cColonKeyword_4; }
		
		//value=REAL
		public Assignment getValueAssignment_5() { return cValueAssignment_5; }
		
		//REAL
		public RuleCall getValueREALParserRuleCall_5_0() { return cValueREALParserRuleCall_5_0; }
	}
	public class LoopStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.LoopStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoopKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cCountAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cCountAdditionParserRuleCall_1_0 = (RuleCall)cCountAssignment_1.eContents().get(0);
		private final Keyword cTimesKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cDoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cStatementsAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cStatementsStatementParserRuleCall_4_0 = (RuleCall)cStatementsAssignment_4.eContents().get(0);
		private final Keyword cEndKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//LoopStatement:
		//    "loop" count = Addition "times" "do"
		//        statements += Statement+
		//    "end"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"loop" count = Addition "times" "do"
		//    statements += Statement+
		//"end"
		public Group getGroup() { return cGroup; }
		
		//"loop"
		public Keyword getLoopKeyword_0() { return cLoopKeyword_0; }
		
		//count = Addition
		public Assignment getCountAssignment_1() { return cCountAssignment_1; }
		
		//Addition
		public RuleCall getCountAdditionParserRuleCall_1_0() { return cCountAdditionParserRuleCall_1_0; }
		
		//"times"
		public Keyword getTimesKeyword_2() { return cTimesKeyword_2; }
		
		//"do"
		public Keyword getDoKeyword_3() { return cDoKeyword_3; }
		
		//statements += Statement+
		public Assignment getStatementsAssignment_4() { return cStatementsAssignment_4; }
		
		//Statement
		public RuleCall getStatementsStatementParserRuleCall_4_0() { return cStatementsStatementParserRuleCall_4_0; }
		
		//"end"
		public Keyword getEndKeyword_5() { return cEndKeyword_5; }
	}
	public class REALElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.REAL");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Keyword cFullStopKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//REAL returns ecore::EFloat hidden():
		//    INT? "." INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//INT? "." INT
		public Group getGroup() { return cGroup; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//"."
		public Keyword getFullStopKeyword_1() { return cFullStopKeyword_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	public class AdditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.Addition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMultiplicationParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAdditionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOperatorAlternatives_1_1_0 = (Alternatives)cOperatorAssignment_1_1.eContents().get(0);
		private final Keyword cOperatorPlusSignKeyword_1_1_0_0 = (Keyword)cOperatorAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOperatorHyphenMinusKeyword_1_1_0_1 = (Keyword)cOperatorAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightMultiplicationParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Addition returns IntExpression:
		//    Multiplication ({Addition.left = current} operator+=("+"|"-") right+=Multiplication)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Multiplication ({Addition.left = current} operator+=("+"|"-") right+=Multiplication)*
		public Group getGroup() { return cGroup; }
		
		//Multiplication
		public RuleCall getMultiplicationParserRuleCall_0() { return cMultiplicationParserRuleCall_0; }
		
		//({Addition.left = current} operator+=("+"|"-") right+=Multiplication)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Addition.left = current}
		public Action getAdditionLeftAction_1_0() { return cAdditionLeftAction_1_0; }
		
		//operator+=("+"|"-")
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//("+"|"-")
		public Alternatives getOperatorAlternatives_1_1_0() { return cOperatorAlternatives_1_1_0; }
		
		//"+"
		public Keyword getOperatorPlusSignKeyword_1_1_0_0() { return cOperatorPlusSignKeyword_1_1_0_0; }
		
		//"-"
		public Keyword getOperatorHyphenMinusKeyword_1_1_0_1() { return cOperatorHyphenMinusKeyword_1_1_0_1; }
		
		//right+=Multiplication
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Multiplication
		public RuleCall getRightMultiplicationParserRuleCall_1_2_0() { return cRightMultiplicationParserRuleCall_1_2_0; }
	}
	public class MultiplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.Multiplication");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cMultiplicationLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOperatorAlternatives_1_1_0 = (Alternatives)cOperatorAssignment_1_1.eContents().get(0);
		private final Keyword cOperatorAsteriskKeyword_1_1_0_0 = (Keyword)cOperatorAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOperatorSolidusKeyword_1_1_0_1 = (Keyword)cOperatorAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Multiplication returns IntExpression:
		//    Primary ({Multiplication.left = current} operator+=("*"|"/") right+=Primary)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Primary ({Multiplication.left = current} operator+=("*"|"/") right+=Primary)*
		public Group getGroup() { return cGroup; }
		
		//Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }
		
		//({Multiplication.left = current} operator+=("*"|"/") right+=Primary)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Multiplication.left = current}
		public Action getMultiplicationLeftAction_1_0() { return cMultiplicationLeftAction_1_0; }
		
		//operator+=("*"|"/")
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//("*"|"/")
		public Alternatives getOperatorAlternatives_1_1_0() { return cOperatorAlternatives_1_1_0; }
		
		//"*"
		public Keyword getOperatorAsteriskKeyword_1_1_0_0() { return cOperatorAsteriskKeyword_1_1_0_0; }
		
		//"/"
		public Keyword getOperatorSolidusKeyword_1_1_0_1() { return cOperatorSolidusKeyword_1_1_0_1; }
		
		//right+=Primary
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Primary
		public RuleCall getRightPrimaryParserRuleCall_1_2_0() { return cRightPrimaryParserRuleCall_1_2_0; }
	}
	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntVarExpressionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final RuleCall cAdditionParserRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//Primary returns IntExpression:
		//    IntLiteral |
		//    IntVarExpression |
		//    "(" Addition ")"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//IntLiteral |
		//IntVarExpression |
		//"(" Addition ")"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntLiteral
		public RuleCall getIntLiteralParserRuleCall_0() { return cIntLiteralParserRuleCall_0; }
		
		//IntVarExpression
		public RuleCall getIntVarExpressionParserRuleCall_1() { return cIntVarExpressionParserRuleCall_1; }
		
		//"(" Addition ")"
		public Group getGroup_2() { return cGroup_2; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_2_0() { return cLeftParenthesisKeyword_2_0; }
		
		//Addition
		public RuleCall getAdditionParserRuleCall_2_1() { return cAdditionParserRuleCall_2_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_2_2() { return cRightParenthesisKeyword_2_2; }
	}
	public class IntLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.IntLiteral");
		private final Assignment cValAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValINTTerminalRuleCall_0 = (RuleCall)cValAssignment.eContents().get(0);
		
		//IntLiteral:
		//    val = INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//val = INT
		public Assignment getValAssignment() { return cValAssignment; }
		
		//INT
		public RuleCall getValINTTerminalRuleCall_0() { return cValINTTerminalRuleCall_0; }
	}
	public class IntVarExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.IntVarExpression");
		private final Assignment cVarAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cVarIntVariableDeclarationCrossReference_0 = (CrossReference)cVarAssignment.eContents().get(0);
		private final RuleCall cVarIntVariableDeclarationIDTerminalRuleCall_0_1 = (RuleCall)cVarIntVariableDeclarationCrossReference_0.eContents().get(1);
		
		//IntVarExpression:
		//    var = [IntVariableDeclaration]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//var = [IntVariableDeclaration]
		public Assignment getVarAssignment() { return cVarAssignment; }
		
		//[IntVariableDeclaration]
		public CrossReference getVarIntVariableDeclarationCrossReference_0() { return cVarIntVariableDeclarationCrossReference_0; }
		
		//ID
		public RuleCall getVarIntVariableDeclarationIDTerminalRuleCall_0_1() { return cVarIntVariableDeclarationIDTerminalRuleCall_0_1; }
	}
	public class ActionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.Action");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBuyParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSellParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Action:
		//    Buy | Sell
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Buy | Sell
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Buy
		public RuleCall getBuyParserRuleCall_0() { return cBuyParserRuleCall_0; }
		
		//Sell
		public RuleCall getSellParserRuleCall_1() { return cSellParserRuleCall_1; }
	}
	public class BuyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.Buy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBuyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cQuantityAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cQuantityREALParserRuleCall_1_0 = (RuleCall)cQuantityAssignment_1.eContents().get(0);
		private final Assignment cTickerAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTickerIDTerminalRuleCall_2_0 = (RuleCall)cTickerAssignment_2.eContents().get(0);
		private final Keyword cAtKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cPriceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPriceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPriceREALParserRuleCall_5_0 = (RuleCall)cPriceAssignment_5.eContents().get(0);
		
		//Buy:
		//    "buy" quantity=REAL ticker=ID "at" "price" price=REAL
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"buy" quantity=REAL ticker=ID "at" "price" price=REAL
		public Group getGroup() { return cGroup; }
		
		//"buy"
		public Keyword getBuyKeyword_0() { return cBuyKeyword_0; }
		
		//quantity=REAL
		public Assignment getQuantityAssignment_1() { return cQuantityAssignment_1; }
		
		//REAL
		public RuleCall getQuantityREALParserRuleCall_1_0() { return cQuantityREALParserRuleCall_1_0; }
		
		//ticker=ID
		public Assignment getTickerAssignment_2() { return cTickerAssignment_2; }
		
		//ID
		public RuleCall getTickerIDTerminalRuleCall_2_0() { return cTickerIDTerminalRuleCall_2_0; }
		
		//"at"
		public Keyword getAtKeyword_3() { return cAtKeyword_3; }
		
		//"price"
		public Keyword getPriceKeyword_4() { return cPriceKeyword_4; }
		
		//price=REAL
		public Assignment getPriceAssignment_5() { return cPriceAssignment_5; }
		
		//REAL
		public RuleCall getPriceREALParserRuleCall_5_0() { return cPriceREALParserRuleCall_5_0; }
	}
	public class SellElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.Sell");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSellKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cQuantityAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cQuantityREALParserRuleCall_1_0 = (RuleCall)cQuantityAssignment_1.eContents().get(0);
		private final Assignment cTickerAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTickerIDTerminalRuleCall_2_0 = (RuleCall)cTickerAssignment_2.eContents().get(0);
		private final Keyword cAtKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cPriceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cPriceAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cPriceREALParserRuleCall_5_0 = (RuleCall)cPriceAssignment_5.eContents().get(0);
		
		//Sell:
		//    "sell" quantity=REAL ticker=ID "at" "price" price=REAL
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"sell" quantity=REAL ticker=ID "at" "price" price=REAL
		public Group getGroup() { return cGroup; }
		
		//"sell"
		public Keyword getSellKeyword_0() { return cSellKeyword_0; }
		
		//quantity=REAL
		public Assignment getQuantityAssignment_1() { return cQuantityAssignment_1; }
		
		//REAL
		public RuleCall getQuantityREALParserRuleCall_1_0() { return cQuantityREALParserRuleCall_1_0; }
		
		//ticker=ID
		public Assignment getTickerAssignment_2() { return cTickerAssignment_2; }
		
		//ID
		public RuleCall getTickerIDTerminalRuleCall_2_0() { return cTickerIDTerminalRuleCall_2_0; }
		
		//"at"
		public Keyword getAtKeyword_3() { return cAtKeyword_3; }
		
		//"price"
		public Keyword getPriceKeyword_4() { return cPriceKeyword_4; }
		
		//price=REAL
		public Assignment getPriceAssignment_5() { return cPriceAssignment_5; }
		
		//REAL
		public RuleCall getPriceREALParserRuleCall_5_0() { return cPriceREALParserRuleCall_5_0; }
	}
	
	public class StrategyDefElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "uk.ac.kcl.inf.trader.Trader.StrategyDef");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cBuyAndHoldEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cBuyAndHoldBuyAndHoldKeyword_0_0 = (Keyword)cBuyAndHoldEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cMeanReversionEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cMeanReversionMeanReversionKeyword_1_0 = (Keyword)cMeanReversionEnumLiteralDeclaration_1.eContents().get(0);
		
		//enum StrategyDef:
		//    buyAndHold | meanReversion
		//;
		public EnumRule getRule() { return rule; }
		
		//buyAndHold | meanReversion
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//buyAndHold
		public EnumLiteralDeclaration getBuyAndHoldEnumLiteralDeclaration_0() { return cBuyAndHoldEnumLiteralDeclaration_0; }
		
		public Keyword getBuyAndHoldBuyAndHoldKeyword_0_0() { return cBuyAndHoldBuyAndHoldKeyword_0_0; }
		
		//meanReversion
		public EnumLiteralDeclaration getMeanReversionEnumLiteralDeclaration_1() { return cMeanReversionEnumLiteralDeclaration_1; }
		
		public Keyword getMeanReversionMeanReversionKeyword_1_0() { return cMeanReversionMeanReversionKeyword_1_0; }
	}
	
	private final TraderProgramElements pTraderProgram;
	private final StatementElements pStatement;
	private final ConnectElements pConnect;
	private final ConnectParametersElements pConnectParameters;
	private final TradingBotElements pTradingBot;
	private final StrategyDefElements eStrategyDef;
	private final ListBotsElements pListBots;
	private final ExecuteElements pExecute;
	private final StopElements pStop;
	private final VariableDeclarationElements pVariableDeclaration;
	private final IntVariableDeclarationElements pIntVariableDeclaration;
	private final StringVariableDeclarationElements pStringVariableDeclaration;
	private final RealVariableDeclarationElements pRealVariableDeclaration;
	private final LoopStatementElements pLoopStatement;
	private final REALElements pREAL;
	private final AdditionElements pAddition;
	private final MultiplicationElements pMultiplication;
	private final PrimaryElements pPrimary;
	private final IntLiteralElements pIntLiteral;
	private final IntVarExpressionElements pIntVarExpression;
	private final ActionElements pAction;
	private final BuyElements pBuy;
	private final SellElements pSell;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public TraderGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pTraderProgram = new TraderProgramElements();
		this.pStatement = new StatementElements();
		this.pConnect = new ConnectElements();
		this.pConnectParameters = new ConnectParametersElements();
		this.pTradingBot = new TradingBotElements();
		this.eStrategyDef = new StrategyDefElements();
		this.pListBots = new ListBotsElements();
		this.pExecute = new ExecuteElements();
		this.pStop = new StopElements();
		this.pVariableDeclaration = new VariableDeclarationElements();
		this.pIntVariableDeclaration = new IntVariableDeclarationElements();
		this.pStringVariableDeclaration = new StringVariableDeclarationElements();
		this.pRealVariableDeclaration = new RealVariableDeclarationElements();
		this.pLoopStatement = new LoopStatementElements();
		this.pREAL = new REALElements();
		this.pAddition = new AdditionElements();
		this.pMultiplication = new MultiplicationElements();
		this.pPrimary = new PrimaryElements();
		this.pIntLiteral = new IntLiteralElements();
		this.pIntVarExpression = new IntVarExpressionElements();
		this.pAction = new ActionElements();
		this.pBuy = new BuyElements();
		this.pSell = new SellElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("uk.ac.kcl.inf.trader.Trader".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//TraderProgram:
	//    statements+=Statement*
	//;
	public TraderProgramElements getTraderProgramAccess() {
		return pTraderProgram;
	}
	
	public ParserRule getTraderProgramRule() {
		return getTraderProgramAccess().getRule();
	}
	
	//Statement:
	//    Connect | TradingBot | ListBots | Execute | Stop | VariableDeclaration | LoopStatement
	//;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//Connect:
	//    "connect" "to" "broker" brokerName = ID "with" ( parameters=ConnectParameters)?
	//;
	public ConnectElements getConnectAccess() {
		return pConnect;
	}
	
	public ParserRule getConnectRule() {
		return getConnectAccess().getRule();
	}
	
	//ConnectParameters:
	//    "username" username=STRING ","
	//    "password" password=STRING ","
	//    "leverage" leverage=REAL ","
	//    "money" money=REAL ","
	//    "timeframe" timeframe=STRING
	//;
	public ConnectParametersElements getConnectParametersAccess() {
		return pConnectParameters;
	}
	
	public ParserRule getConnectParametersRule() {
		return getConnectParametersAccess().getRule();
	}
	
	//TradingBot:
	//    "create" "bot" botName = ID "with" strategy = StrategyDef "strategy" "using" funds = REAL "from" "money"
	//;
	public TradingBotElements getTradingBotAccess() {
		return pTradingBot;
	}
	
	public ParserRule getTradingBotRule() {
		return getTradingBotAccess().getRule();
	}
	
	//enum StrategyDef:
	//    buyAndHold | meanReversion
	//;
	public StrategyDefElements getStrategyDefAccess() {
		return eStrategyDef;
	}
	
	public EnumRule getStrategyDefRule() {
		return getStrategyDefAccess().getRule();
	}
	
	//ListBots:
	//    listCommand = "see" "registered" "bots"
	//;
	public ListBotsElements getListBotsAccess() {
		return pListBots;
	}
	
	public ParserRule getListBotsRule() {
		return getListBotsAccess().getRule();
	}
	
	//Execute:
	//    executeCommand = "execute" "bots"
	//;
	public ExecuteElements getExecuteAccess() {
		return pExecute;
	}
	
	public ParserRule getExecuteRule() {
		return getExecuteAccess().getRule();
	}
	
	//Stop:
	//    stopCommand = "stop" "bots"
	//;
	public StopElements getStopAccess() {
		return pStop;
	}
	
	public ParserRule getStopRule() {
		return getStopAccess().getRule();
	}
	
	//VariableDeclaration:
	//    IntVariableDeclaration | StringVariableDeclaration | RealVariableDeclaration
	//;
	public VariableDeclarationElements getVariableDeclarationAccess() {
		return pVariableDeclaration;
	}
	
	public ParserRule getVariableDeclarationRule() {
		return getVariableDeclarationAccess().getRule();
	}
	
	//IntVariableDeclaration:
	//    "var" name=ID "=" "int" ":" value=INT
	//;
	public IntVariableDeclarationElements getIntVariableDeclarationAccess() {
		return pIntVariableDeclaration;
	}
	
	public ParserRule getIntVariableDeclarationRule() {
		return getIntVariableDeclarationAccess().getRule();
	}
	
	//StringVariableDeclaration:
	//    "var" name=ID "=" "String" ":" value=STRING
	//;
	public StringVariableDeclarationElements getStringVariableDeclarationAccess() {
		return pStringVariableDeclaration;
	}
	
	public ParserRule getStringVariableDeclarationRule() {
		return getStringVariableDeclarationAccess().getRule();
	}
	
	//RealVariableDeclaration:
	//    "var" name=ID "=" "Real" ":" value=REAL
	//;
	public RealVariableDeclarationElements getRealVariableDeclarationAccess() {
		return pRealVariableDeclaration;
	}
	
	public ParserRule getRealVariableDeclarationRule() {
		return getRealVariableDeclarationAccess().getRule();
	}
	
	//LoopStatement:
	//    "loop" count = Addition "times" "do"
	//        statements += Statement+
	//    "end"
	//;
	public LoopStatementElements getLoopStatementAccess() {
		return pLoopStatement;
	}
	
	public ParserRule getLoopStatementRule() {
		return getLoopStatementAccess().getRule();
	}
	
	//REAL returns ecore::EFloat hidden():
	//    INT? "." INT
	//;
	public REALElements getREALAccess() {
		return pREAL;
	}
	
	public ParserRule getREALRule() {
		return getREALAccess().getRule();
	}
	
	//Addition returns IntExpression:
	//    Multiplication ({Addition.left = current} operator+=("+"|"-") right+=Multiplication)*
	//;
	public AdditionElements getAdditionAccess() {
		return pAddition;
	}
	
	public ParserRule getAdditionRule() {
		return getAdditionAccess().getRule();
	}
	
	//Multiplication returns IntExpression:
	//    Primary ({Multiplication.left = current} operator+=("*"|"/") right+=Primary)*
	//;
	public MultiplicationElements getMultiplicationAccess() {
		return pMultiplication;
	}
	
	public ParserRule getMultiplicationRule() {
		return getMultiplicationAccess().getRule();
	}
	
	//Primary returns IntExpression:
	//    IntLiteral |
	//    IntVarExpression |
	//    "(" Addition ")"
	//;
	public PrimaryElements getPrimaryAccess() {
		return pPrimary;
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}
	
	//IntLiteral:
	//    val = INT
	//;
	public IntLiteralElements getIntLiteralAccess() {
		return pIntLiteral;
	}
	
	public ParserRule getIntLiteralRule() {
		return getIntLiteralAccess().getRule();
	}
	
	//IntVarExpression:
	//    var = [IntVariableDeclaration]
	//;
	public IntVarExpressionElements getIntVarExpressionAccess() {
		return pIntVarExpression;
	}
	
	public ParserRule getIntVarExpressionRule() {
		return getIntVarExpressionAccess().getRule();
	}
	
	//Action:
	//    Buy | Sell
	//;
	public ActionElements getActionAccess() {
		return pAction;
	}
	
	public ParserRule getActionRule() {
		return getActionAccess().getRule();
	}
	
	//Buy:
	//    "buy" quantity=REAL ticker=ID "at" "price" price=REAL
	//;
	public BuyElements getBuyAccess() {
		return pBuy;
	}
	
	public ParserRule getBuyRule() {
		return getBuyAccess().getRule();
	}
	
	//Sell:
	//    "sell" quantity=REAL ticker=ID "at" "price" price=REAL
	//;
	public SellElements getSellAccess() {
		return pSell;
	}
	
	public ParserRule getSellRule() {
		return getSellAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
