/*
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
class TraderProposalProvider extends AbstractTraderProposalProvider {
}
