/*
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import uk.ac.kcl.inf.trader.TraderRuntimeModule
import uk.ac.kcl.inf.trader.TraderStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TraderIdeSetup extends TraderStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TraderRuntimeModule, new TraderIdeModule))
	}
	
}
