/*
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class TraderUiModule extends AbstractTraderUiModule {
}
