/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.trader.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class TraderUiModule extends AbstractTraderUiModule {

	public TraderUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
