/*
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uk.ac.kcl.inf.trader.ide.contentassist.antlr.internal.InternalTraderParser;
import uk.ac.kcl.inf.trader.services.TraderGrammarAccess;

public class TraderParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TraderGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TraderGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getStatementAccess().getAlternatives(), "rule__Statement__Alternatives");
			builder.put(grammarAccess.getVariableDeclarationAccess().getAlternatives_3(), "rule__VariableDeclaration__Alternatives_3");
			builder.put(grammarAccess.getAdditionAccess().getOperatorAlternatives_1_1_0(), "rule__Addition__OperatorAlternatives_1_1_0");
			builder.put(grammarAccess.getMultiplicationAccess().getOperatorAlternatives_1_1_0(), "rule__Multiplication__OperatorAlternatives_1_1_0");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getStringPrimaryAccess().getAlternatives(), "rule__StringPrimary__Alternatives");
			builder.put(grammarAccess.getActionAccess().getAlternatives(), "rule__Action__Alternatives");
			builder.put(grammarAccess.getStrategyDefAccess().getAlternatives(), "rule__StrategyDef__Alternatives");
			builder.put(grammarAccess.getConnectStatementAccess().getGroup(), "rule__ConnectStatement__Group__0");
			builder.put(grammarAccess.getTradingBotAccess().getGroup(), "rule__TradingBot__Group__0");
			builder.put(grammarAccess.getListBotsAccess().getGroup(), "rule__ListBots__Group__0");
			builder.put(grammarAccess.getExecuteAccess().getGroup(), "rule__Execute__Group__0");
			builder.put(grammarAccess.getStopAccess().getGroup(), "rule__Stop__Group__0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getGroup(), "rule__VariableDeclaration__Group__0");
			builder.put(grammarAccess.getLoopStatementAccess().getGroup(), "rule__LoopStatement__Group__0");
			builder.put(grammarAccess.getREALAccess().getGroup(), "rule__REAL__Group__0");
			builder.put(grammarAccess.getAdditionAccess().getGroup(), "rule__Addition__Group__0");
			builder.put(grammarAccess.getAdditionAccess().getGroup_1(), "rule__Addition__Group_1__0");
			builder.put(grammarAccess.getMultiplicationAccess().getGroup(), "rule__Multiplication__Group__0");
			builder.put(grammarAccess.getMultiplicationAccess().getGroup_1(), "rule__Multiplication__Group_1__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_3(), "rule__Primary__Group_3__0");
			builder.put(grammarAccess.getBuyAccess().getGroup(), "rule__Buy__Group__0");
			builder.put(grammarAccess.getSellAccess().getGroup(), "rule__Sell__Group__0");
			builder.put(grammarAccess.getTraderProgramAccess().getStatementsAssignment(), "rule__TraderProgram__StatementsAssignment");
			builder.put(grammarAccess.getConnectStatementAccess().getBrokerNameAssignment_3(), "rule__ConnectStatement__BrokerNameAssignment_3");
			builder.put(grammarAccess.getConnectStatementAccess().getUsernameAssignment_6(), "rule__ConnectStatement__UsernameAssignment_6");
			builder.put(grammarAccess.getConnectStatementAccess().getPasswordAssignment_9(), "rule__ConnectStatement__PasswordAssignment_9");
			builder.put(grammarAccess.getConnectStatementAccess().getLeverageAssignment_12(), "rule__ConnectStatement__LeverageAssignment_12");
			builder.put(grammarAccess.getConnectStatementAccess().getMoneyAssignment_15(), "rule__ConnectStatement__MoneyAssignment_15");
			builder.put(grammarAccess.getConnectStatementAccess().getTimeframeAssignment_18(), "rule__ConnectStatement__TimeframeAssignment_18");
			builder.put(grammarAccess.getTradingBotAccess().getStrategyAssignment_3(), "rule__TradingBot__StrategyAssignment_3");
			builder.put(grammarAccess.getTradingBotAccess().getFundAssignment_6(), "rule__TradingBot__FundAssignment_6");
			builder.put(grammarAccess.getListBotsAccess().getListCommandAssignment_0(), "rule__ListBots__ListCommandAssignment_0");
			builder.put(grammarAccess.getExecuteAccess().getExecuteCommandAssignment_0(), "rule__Execute__ExecuteCommandAssignment_0");
			builder.put(grammarAccess.getStopAccess().getStopCommandAssignment_0(), "rule__Stop__StopCommandAssignment_0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getNameAssignment_1(), "rule__VariableDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getVariableDeclarationAccess().getValueAssignment_3_0(), "rule__VariableDeclaration__ValueAssignment_3_0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getValueAssignment_3_1(), "rule__VariableDeclaration__ValueAssignment_3_1");
			builder.put(grammarAccess.getVariableDeclarationAccess().getValueAssignment_3_2(), "rule__VariableDeclaration__ValueAssignment_3_2");
			builder.put(grammarAccess.getStringValueAccess().getValueAssignment(), "rule__StringValue__ValueAssignment");
			builder.put(grammarAccess.getRealValueAccess().getValueAssignment(), "rule__RealValue__ValueAssignment");
			builder.put(grammarAccess.getIntValueAccess().getValueAssignment(), "rule__IntValue__ValueAssignment");
			builder.put(grammarAccess.getLoopStatementAccess().getCountAssignment_1(), "rule__LoopStatement__CountAssignment_1");
			builder.put(grammarAccess.getLoopStatementAccess().getStatementsAssignment_4(), "rule__LoopStatement__StatementsAssignment_4");
			builder.put(grammarAccess.getAdditionAccess().getOperatorAssignment_1_1(), "rule__Addition__OperatorAssignment_1_1");
			builder.put(grammarAccess.getAdditionAccess().getRightAssignment_1_2(), "rule__Addition__RightAssignment_1_2");
			builder.put(grammarAccess.getMultiplicationAccess().getOperatorAssignment_1_1(), "rule__Multiplication__OperatorAssignment_1_1");
			builder.put(grammarAccess.getMultiplicationAccess().getRightAssignment_1_2(), "rule__Multiplication__RightAssignment_1_2");
			builder.put(grammarAccess.getNumVarExpressionAccess().getVarAssignment(), "rule__NumVarExpression__VarAssignment");
			builder.put(grammarAccess.getStringVarExpressionAccess().getVarAssignment(), "rule__StringVarExpression__VarAssignment");
			builder.put(grammarAccess.getBuyAccess().getQuantityAssignment_1(), "rule__Buy__QuantityAssignment_1");
			builder.put(grammarAccess.getBuyAccess().getTickerAssignment_2(), "rule__Buy__TickerAssignment_2");
			builder.put(grammarAccess.getBuyAccess().getPriceAssignment_5(), "rule__Buy__PriceAssignment_5");
			builder.put(grammarAccess.getSellAccess().getQuantityAssignment_1(), "rule__Sell__QuantityAssignment_1");
			builder.put(grammarAccess.getSellAccess().getTickerAssignment_2(), "rule__Sell__TickerAssignment_2");
			builder.put(grammarAccess.getSellAccess().getPriceAssignment_5(), "rule__Sell__PriceAssignment_5");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TraderGrammarAccess grammarAccess;

	@Override
	protected InternalTraderParser createParser() {
		InternalTraderParser result = new InternalTraderParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TraderGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TraderGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
