/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.trader;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class TraderStandaloneSetup extends TraderStandaloneSetupGenerated {

	public static void doSetup() {
		new TraderStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
