/*
 * generated by Xtext 2.34.0
 */
package uk.ac.kcl.inf.trader


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TraderRuntimeModule extends AbstractTraderRuntimeModule {
}
