/*
 * generated by Xtext 2.33.0
 */
package uk.ac.kcl.inf.trader;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TraderRuntimeModule extends AbstractTraderRuntimeModule {
}
